// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0uX_9WSvFf3WxomPijAlI9ovKOsiLvCQ',
    appId: '1:20687703952:web:6a662299d02e774d89ad15',
    messagingSenderId: '20687703952',
    projectId: 'auth-1c2eb',
    authDomain: 'auth-1c2eb.firebaseapp.com',
    storageBucket: 'auth-1c2eb.appspot.com',
    measurementId: 'G-032E94ESCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6bHflv_Fw3s_Nx-aun6VGMdlnoBd5qc',
    appId: '1:20687703952:android:1580dd698e6fc27389ad15',
    messagingSenderId: '20687703952',
    projectId: 'auth-1c2eb',
    storageBucket: 'auth-1c2eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5pW8MX9O1r1qV830pyRUJvZXMWIiyEoc',
    appId: '1:20687703952:ios:4d726a6e98d4baf889ad15',
    messagingSenderId: '20687703952',
    projectId: 'auth-1c2eb',
    storageBucket: 'auth-1c2eb.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5pW8MX9O1r1qV830pyRUJvZXMWIiyEoc',
    appId: '1:20687703952:ios:4d726a6e98d4baf889ad15',
    messagingSenderId: '20687703952',
    projectId: 'auth-1c2eb',
    storageBucket: 'auth-1c2eb.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0uX_9WSvFf3WxomPijAlI9ovKOsiLvCQ',
    appId: '1:20687703952:web:d3685e250d0965ab89ad15',
    messagingSenderId: '20687703952',
    projectId: 'auth-1c2eb',
    authDomain: 'auth-1c2eb.firebaseapp.com',
    storageBucket: 'auth-1c2eb.appspot.com',
    measurementId: 'G-RJ3RGP8BXH',
  );
}
